"""
Menu seeder — Indian + American cuisine.
Run standalone: python seed_menu.py
Or called automatically by app startup if menu is empty.
"""

import asyncio
from app.core.prisma import prisma

MENU_DATA = [
    # ─────────────────────────── INDIAN — Biryani ───────────────────────────
    {
        "name": "Chicken Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Fragrant basmati rice slow-cooked with tender chicken, saffron, and whole spices",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "dairy",
    },
    {
        "name": "Mutton Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Slow-cooked dum biryani with succulent mutton pieces and aromatic spices",
        "price": 340.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "dairy",
    },
    {
        "name": "Veg Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Garden vegetables and paneer cooked with saffron basmati rice",
        "price": 220.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "dairy",
    },
    {
        "name": "Egg Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Fluffy basmati rice with boiled eggs and biryani masala",
        "price": 200.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "eggs",
    },
    # ─────────────────────────── INDIAN — Curries ────────────────────────────
    {
        "name": "Butter Chicken",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Creamy tomato-based curry with tender chicken in a rich buttery sauce",
        "price": 260.0,
        "is_vegetarian": False,
        "spice_level": "mild",
        "allergens": "dairy",
    },
    {
        "name": "Chicken Tikka Masala",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Grilled chicken tikka simmered in a spiced tomato-cream gravy",
        "price": 270.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "dairy",
    },
    {
        "name": "Palak Paneer",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Cottage cheese cubes in a smooth, spiced spinach gravy",
        "price": 220.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "dairy",
    },
    {
        "name": "Dal Makhani",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Slow-cooked black lentils with butter and cream — a classic comfort dish",
        "price": 190.0,
        "is_vegetarian": True,
        "is_vegan": False,
        "spice_level": "mild",
        "allergens": "dairy",
    },
    {
        "name": "Chicken 65",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Deep-fried spicy chicken bites marinated in ginger, garlic, and red chillies",
        "price": 220.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "eggs",
    },
    {
        "name": "Paneer Tikka",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Grilled cottage cheese cubes marinated in yogurt and spices",
        "price": 200.0,
        "is_vegetarian": True,
        "spice_level": "medium",
        "allergens": "dairy",
    },
    {
        "name": "Samosa (2 pcs)",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Crispy pastry filled with spiced potatoes and peas, served with chutney",
        "price": 60.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "medium",
        "allergens": "gluten",
    },
    # ─────────────────────────── INDIAN — Breads ─────────────────────────────
    {
        "name": "Butter Naan",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Soft leavened flatbread brushed with butter, baked in tandoor",
        "price": 50.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
    },
    {
        "name": "Garlic Naan",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Tandoor-baked naan topped with fresh garlic and coriander",
        "price": 60.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
    },
    {
        "name": "Plain Paratha",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Whole wheat flatbread pan-fried with ghee",
        "price": 40.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
    },
    # ─────────────────────────── INDIAN — Rice ───────────────────────────────
    {
        "name": "Steamed Basmati Rice",
        "category": "Rice",
        "cuisine": "indian",
        "description": "Fluffy long-grain basmati rice",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
    },
    {
        "name": "Jeera Rice",
        "category": "Rice",
        "cuisine": "indian",
        "description": "Cumin-tempered basmati rice",
        "price": 100.0,
        "is_vegetarian": True,
        "is_vegan": True,
    },
    # ─────────────────────────── INDIAN — Sides ──────────────────────────────
    {
        "name": "Raita",
        "category": "Sides",
        "cuisine": "indian",
        "description": "Chilled yogurt with cucumber, cumin, and mint",
        "price": 60.0,
        "is_vegetarian": True,
        "allergens": "dairy",
    },
    {
        "name": "Papad",
        "category": "Sides",
        "cuisine": "indian",
        "description": "Crispy lentil wafers",
        "price": 30.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
    },
    # ─────────────────────────── INDIAN — Beverages ──────────────────────────
    {
        "name": "Mango Lassi",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Chilled yogurt smoothie blended with fresh Alphonso mango",
        "price": 90.0,
        "is_vegetarian": True,
        "allergens": "dairy",
    },
    {
        "name": "Masala Chai",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Spiced Indian tea with cardamom, ginger, and milk",
        "price": 50.0,
        "is_vegetarian": True,
        "allergens": "dairy",
    },
    {
        "name": "Sweet Lassi",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Classic chilled yogurt drink sweetened with rose water",
        "price": 70.0,
        "is_vegetarian": True,
        "allergens": "dairy",
    },
    # ─────────────────────────── INDIAN — Desserts ───────────────────────────
    {
        "name": "Gulab Jamun (2 pcs)",
        "category": "Desserts",
        "cuisine": "indian",
        "description": "Soft milk-solid dumplings soaked in rose-flavored sugar syrup",
        "price": 80.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten",
    },
    {
        "name": "Kheer",
        "category": "Desserts",
        "cuisine": "indian",
        "description": "Creamy rice pudding with cardamom, saffron, and dry fruits",
        "price": 90.0,
        "is_vegetarian": True,
        "allergens": "dairy, nuts",
    },
    # ─────────────────────────── AMERICAN — Burgers ──────────────────────────
    {
        "name": "Classic Smash Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Smashed beef patty with American cheese, pickles, onion, and special sauce",
        "price": 320.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
    },
    {
        "name": "BBQ Bacon Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Beef patty with crispy bacon, cheddar, caramelized onions, and smoky BBQ sauce",
        "price": 380.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
    },
    {
        "name": "Crispy Chicken Sandwich",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Buttermilk-fried chicken breast with coleslaw and hot honey on a brioche bun",
        "price": 340.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
    },
    {
        "name": "Veggie Beyond Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Plant-based patty with lettuce, tomato, vegan mayo, and pickles",
        "price": 310.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
    },
    # ─────────────────────────── AMERICAN — Sides ────────────────────────────
    {
        "name": "Loaded Cheese Fries",
        "category": "Sides",
        "cuisine": "american",
        "description": "Crispy fries smothered in cheddar cheese sauce with jalapeños and sour cream",
        "price": 180.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten",
    },
    {
        "name": "Onion Rings",
        "category": "Sides",
        "cuisine": "american",
        "description": "Beer-battered golden onion rings with ranch dipping sauce",
        "price": 140.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
    },
    {
        "name": "Classic Coleslaw",
        "category": "Sides",
        "cuisine": "american",
        "description": "Creamy cabbage and carrot slaw",
        "price": 80.0,
        "is_vegetarian": True,
        "allergens": "dairy, eggs",
    },
    # ─────────────────────────── AMERICAN — Starters ─────────────────────────
    {
        "name": "Buffalo Wings (6 pcs)",
        "category": "Starters",
        "cuisine": "american",
        "description": "Crispy chicken wings tossed in spicy buffalo sauce, served with blue cheese dip",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "dairy, gluten",
    },
    {
        "name": "Mac & Cheese Bites",
        "category": "Starters",
        "cuisine": "american",
        "description": "Crispy fried macaroni and cheese balls with chipotle dipping sauce",
        "price": 200.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
    },
    {
        "name": "Caesar Salad",
        "category": "Starters",
        "cuisine": "american",
        "description": "Romaine lettuce with parmesan, croutons, and house Caesar dressing",
        "price": 220.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
    },
    # ─────────────────────────── AMERICAN — Mains ────────────────────────────
    {
        "name": "BBQ Pulled Pork Platter",
        "category": "Mains",
        "cuisine": "american",
        "description": "Slow-smoked pulled pork with hickory BBQ sauce, served with cornbread and coleslaw",
        "price": 420.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy",
    },
    {
        "name": "Grilled Ribeye Steak",
        "category": "Mains",
        "cuisine": "american",
        "description": "250g prime ribeye grilled to your preference, with garlic butter and fries",
        "price": 680.0,
        "is_vegetarian": False,
        "allergens": "dairy",
    },
    {
        "name": "New York Style Pizza (12\")",
        "category": "Mains",
        "cuisine": "american",
        "description": "Classic hand-tossed pizza with mozzarella and your choice of toppings",
        "price": 380.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
    },
    # ─────────────────────────── AMERICAN — Beverages ────────────────────────
    {
        "name": "Classic Milkshake",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Thick and creamy shake — choose from Chocolate, Vanilla, or Strawberry",
        "price": 150.0,
        "is_vegetarian": True,
        "allergens": "dairy",
    },
    {
        "name": "Fresh Lemonade",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Hand-squeezed lemonade with fresh mint",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
    },
    {
        "name": "Craft Root Beer",
        "category": "Beverages",
        "cuisine": "american",
        "description": "House-made old-fashioned root beer",
        "price": 90.0,
        "is_vegetarian": True,
        "is_vegan": True,
    },
    # ─────────────────────────── AMERICAN — Desserts ─────────────────────────
    {
        "name": "New York Cheesecake",
        "category": "Desserts",
        "cuisine": "american",
        "description": "Dense and creamy New York-style cheesecake with berry compote",
        "price": 180.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
    },
    {
        "name": "Warm Brownie Sundae",
        "category": "Desserts",
        "cuisine": "american",
        "description": "Fudgy chocolate brownie with vanilla ice cream and hot fudge sauce",
        "price": 160.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
    },
]


async def seed_menu() -> None:
    for item_data in MENU_DATA:
        await prisma.menuitem.create(data=item_data)
    print(f"Seeded {len(MENU_DATA)} menu items (Indian + American)")


if __name__ == "__main__":
    async def main():
        await prisma.connect()
        try:
            await seed_menu()
        finally:
            await prisma.disconnect()

    asyncio.run(main())
