"""
Menu seeder — Indian + American + Fusion cuisine.
Run standalone: python seed_menu.py
Or called automatically by app startup if menu is empty.

meal_times values (comma-separated): breakfast, brunch, lunch, dinner, snacks, desserts, beverages, all
"""

import asyncio
from app.core.prisma import prisma

MENU_DATA = [
    # ─────────────────────────── INDIAN BREAKFAST ────────────────────────────
    {
        "name": "Masala Dosa",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Crispy rice crepe filled with spiced potato masala, served with sambar and coconut chutney",
        "price": 120.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "medium",
        "allergens": "gluten",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Masala Chai, Filter Coffee",
    },
    {
        "name": "Plain Dosa",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Thin crispy rice crepe served with sambar and coconut chutney",
        "price": 90.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "breakfast,brunch",
        "pairs_with": "Masala Chai, Filter Coffee",
    },
    {
        "name": "Idli (3 pcs)",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Steamed rice cakes served with sambar and coconut chutney",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "breakfast,brunch",
        "pairs_with": "Medu Vada (2 pcs), Masala Chai",
    },
    {
        "name": "Medu Vada (2 pcs)",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Crispy fried lentil doughnuts served with sambar and chutney",
        "price": 90.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Idli (3 pcs), Filter Coffee",
    },
    {
        "name": "Pongal",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Comforting slow-cooked rice and lentil porridge tempered with ghee, pepper, and cumin",
        "price": 100.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Medu Vada (2 pcs), Filter Coffee",
    },
    {
        "name": "Upma",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Semolina porridge tempered with mustard seeds, curry leaves, and vegetables",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "breakfast,brunch",
        "pairs_with": "Filter Coffee, Masala Chai",
    },
    {
        "name": "Aloo Paratha",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Whole wheat flatbread stuffed with spiced mashed potatoes, pan-fried in ghee",
        "price": 110.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "gluten, dairy",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Sweet Lassi, Mixed Pickle",
    },
    {
        "name": "Poha",
        "category": "Breakfast",
        "cuisine": "indian",
        "description": "Flattened rice stir-fried with onions, mustard seeds, turmeric, and peanuts",
        "price": 70.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "nuts",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Masala Chai, Fresh Lime Soda",
    },
    # ─────────────────────────── AMERICAN BREAKFAST ──────────────────────────
    {
        "name": "Buttermilk Pancakes",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Fluffy stack of three buttermilk pancakes with maple syrup and butter",
        "price": 180.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Americano Coffee, Fresh Orange Juice",
    },
    {
        "name": "Belgian Waffles",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Crispy golden waffles with whipped cream, fresh berries, and maple syrup",
        "price": 200.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Americano Coffee, Fresh Orange Juice",
    },
    {
        "name": "French Toast",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Thick-cut brioche dipped in vanilla custard, pan-fried golden, dusted with cinnamon sugar",
        "price": 170.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Cappuccino, Fresh Orange Juice",
    },
    {
        "name": "Classic Omelette",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Three-egg omelette with cheddar, mushrooms, bell peppers, and onions",
        "price": 160.0,
        "is_vegetarian": True,
        "allergens": "dairy, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Americano Coffee, Fresh Orange Juice",
    },
    {
        "name": "Breakfast Sandwich",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Toasted brioche bun with fried egg, cheddar, crispy bacon, and sriracha mayo",
        "price": 220.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Americano Coffee, Fresh Orange Juice",
    },
    {
        "name": "Avocado Toast",
        "category": "Breakfast",
        "cuisine": "american",
        "description": "Smashed avocado on sourdough toast with poached egg, cherry tomatoes, and red chilli flakes",
        "price": 190.0,
        "is_vegetarian": True,
        "allergens": "gluten, eggs",
        "meal_times": "breakfast,brunch",
        "pairs_with": "Cappuccino, Fresh Orange Juice",
    },
    # ─────────────────────────── INDIAN — Biryani ────────────────────────────
    {
        "name": "Chicken Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Fragrant basmati rice slow-cooked with tender chicken, saffron, and whole spices",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Raita, Gulab Jamun (2 pcs)",
    },
    {
        "name": "Mutton Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Slow-cooked dum biryani with succulent mutton pieces and aromatic spices",
        "price": 340.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Raita, Gulab Jamun (2 pcs)",
    },
    {
        "name": "Veg Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Garden vegetables and paneer cooked with saffron basmati rice",
        "price": 220.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Raita, Papad",
    },
    {
        "name": "Egg Biryani",
        "category": "Biryani",
        "cuisine": "indian",
        "description": "Fluffy basmati rice with boiled eggs and biryani masala",
        "price": 200.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "eggs",
        "meal_times": "lunch,dinner",
        "pairs_with": "Raita, Papad",
    },
    # ─────────────────────────── INDIAN — Curries ────────────────────────────
    {
        "name": "Butter Chicken",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Creamy tomato-based curry with tender chicken in a rich buttery sauce",
        "price": 260.0,
        "is_vegetarian": False,
        "spice_level": "mild",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Butter Naan, Garlic Naan, Jeera Rice",
    },
    {
        "name": "Chicken Tikka Masala",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Grilled chicken tikka simmered in a spiced tomato-cream gravy",
        "price": 270.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Garlic Naan, Steamed Basmati Rice",
    },
    {
        "name": "Paneer Butter Masala",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Cottage cheese cubes in a rich, creamy tomato-butter gravy",
        "price": 240.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Butter Naan, Plain Roti",
    },
    {
        "name": "Palak Paneer",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Cottage cheese cubes in a smooth, spiced spinach gravy",
        "price": 220.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Garlic Naan, Jeera Rice",
    },
    {
        "name": "Dal Makhani",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Slow-cooked black lentils with butter and cream — a classic comfort dish",
        "price": 190.0,
        "is_vegetarian": True,
        "is_vegan": False,
        "spice_level": "mild",
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Butter Naan, Steamed Basmati Rice",
    },
    {
        "name": "Kadai Chicken",
        "category": "Curries",
        "cuisine": "indian",
        "description": "Chicken cooked with bell peppers, onions, and a freshly ground kadai masala",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "meal_times": "lunch,dinner",
        "pairs_with": "Butter Naan, Plain Roti",
    },
    # ─────────────────────────── INDIAN — Starters / Snacks ──────────────────
    {
        "name": "Chicken 65",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Deep-fried spicy chicken bites marinated in ginger, garlic, and red chillies",
        "price": 220.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "eggs",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Fresh Lime Soda, Mango Lassi",
    },
    {
        "name": "Paneer Tikka",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Grilled cottage cheese cubes marinated in yogurt and spices",
        "price": 200.0,
        "is_vegetarian": True,
        "spice_level": "medium",
        "allergens": "dairy",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Fresh Lime Soda, Mango Lassi",
    },
    {
        "name": "Samosa (2 pcs)",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Crispy pastry filled with spiced potatoes and peas, served with chutney",
        "price": 60.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "medium",
        "allergens": "gluten",
        "meal_times": "snacks,brunch",
        "pairs_with": "Masala Chai, Sweet Lassi",
    },
    {
        "name": "Pakora Platter",
        "category": "Starters",
        "cuisine": "indian",
        "description": "Assorted vegetable fritters in a spiced chickpea batter, served with mint chutney",
        "price": 130.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "mild",
        "allergens": "gluten",
        "meal_times": "snacks,brunch",
        "pairs_with": "Masala Chai, Fresh Lime Soda",
    },
    # ─────────────────────────── INDIAN — Breads ─────────────────────────────
    {
        "name": "Butter Naan",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Soft leavened flatbread brushed with butter, baked in tandoor",
        "price": 50.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Garlic Naan",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Tandoor-baked naan topped with fresh garlic and coriander",
        "price": 60.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Plain Roti",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Thin whole wheat flatbread, freshly baked",
        "price": 30.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Plain Paratha",
        "category": "Breads",
        "cuisine": "indian",
        "description": "Whole wheat flatbread pan-fried with ghee",
        "price": 40.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "breakfast,brunch,lunch,dinner",
    },
    # ─────────────────────────── INDIAN — Rice ───────────────────────────────
    {
        "name": "Steamed Basmati Rice",
        "category": "Rice",
        "cuisine": "indian",
        "description": "Fluffy long-grain basmati rice",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Jeera Rice",
        "category": "Rice",
        "cuisine": "indian",
        "description": "Cumin-tempered basmati rice",
        "price": 100.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "lunch,dinner",
    },
    # ─────────────────────────── INDIAN — Sides ──────────────────────────────
    {
        "name": "Raita",
        "category": "Sides",
        "cuisine": "indian",
        "description": "Chilled yogurt with cucumber, cumin, and mint",
        "price": 60.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Papad",
        "category": "Sides",
        "cuisine": "indian",
        "description": "Crispy lentil wafers",
        "price": 30.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Mixed Pickle",
        "category": "Sides",
        "cuisine": "indian",
        "description": "Tangy house-made mixed vegetable pickle",
        "price": 40.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "lunch,dinner",
    },
    # ─────────────────────────── INDIAN — Beverages ──────────────────────────
    {
        "name": "Mango Lassi",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Chilled yogurt smoothie blended with fresh Alphonso mango",
        "price": 90.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "all",
    },
    {
        "name": "Masala Chai",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Spiced Indian tea with cardamom, ginger, and milk",
        "price": 50.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "all",
    },
    {
        "name": "Sweet Lassi",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Classic chilled yogurt drink sweetened with rose water",
        "price": 70.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "all",
    },
    {
        "name": "Fresh Lime Soda",
        "category": "Beverages",
        "cuisine": "indian",
        "description": "Hand-squeezed lime with soda, choice of sweet or salted",
        "price": 60.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "all",
    },
    # ─────────────────────────── INDIAN — Desserts ───────────────────────────
    {
        "name": "Gulab Jamun (2 pcs)",
        "category": "Desserts",
        "cuisine": "indian",
        "description": "Soft milk-solid dumplings soaked in rose-flavored sugar syrup",
        "price": 80.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten",
        "meal_times": "desserts,lunch,dinner",
        "pairs_with": "Masala Chai",
    },
    {
        "name": "Kheer",
        "category": "Desserts",
        "cuisine": "indian",
        "description": "Creamy rice pudding with cardamom, saffron, and dry fruits",
        "price": 90.0,
        "is_vegetarian": True,
        "allergens": "dairy, nuts",
        "meal_times": "desserts,lunch,dinner",
        "pairs_with": "Masala Chai",
    },
    # ─────────────────────────── AMERICAN — Burgers ──────────────────────────
    {
        "name": "Classic Smash Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Smashed beef patty with American cheese, pickles, onion, and special sauce",
        "price": 320.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Classic Fries, Onion Rings",
    },
    {
        "name": "BBQ Bacon Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Beef patty with crispy bacon, cheddar, caramelized onions, and smoky BBQ sauce",
        "price": 380.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "lunch,dinner",
        "pairs_with": "Classic Fries, Onion Rings",
    },
    {
        "name": "Crispy Chicken Sandwich",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Buttermilk-fried chicken breast with coleslaw and hot honey on a brioche bun",
        "price": 340.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy, eggs",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Loaded Cheese Fries, Classic Milkshake",
    },
    {
        "name": "Veggie Beyond Burger",
        "category": "Burgers",
        "cuisine": "american",
        "description": "Plant-based patty with lettuce, tomato, vegan mayo, and pickles",
        "price": 310.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Classic Fries, Fresh Lemonade",
    },
    # ─────────────────────────── AMERICAN — Sides ────────────────────────────
    {
        "name": "Loaded Cheese Fries",
        "category": "Sides",
        "cuisine": "american",
        "description": "Crispy fries smothered in cheddar cheese sauce with jalapeños and sour cream",
        "price": 180.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Craft Root Beer, Fresh Lemonade",
    },
    {
        "name": "Classic Fries",
        "category": "Sides",
        "cuisine": "american",
        "description": "Golden crispy seasoned fries",
        "price": 120.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "allergens": "gluten",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Classic Milkshake, Craft Root Beer",
    },
    {
        "name": "Onion Rings",
        "category": "Sides",
        "cuisine": "american",
        "description": "Beer-battered golden onion rings with ranch dipping sauce",
        "price": 140.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Fresh Lemonade, Classic Milkshake",
    },
    {
        "name": "Classic Coleslaw",
        "category": "Sides",
        "cuisine": "american",
        "description": "Creamy cabbage and carrot slaw",
        "price": 80.0,
        "is_vegetarian": True,
        "allergens": "dairy, eggs",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Garlic Bread",
        "category": "Sides",
        "cuisine": "american",
        "description": "Toasted sourdough with garlic herb butter",
        "price": 90.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
    },
    # ─────────────────────────── AMERICAN — Starters ─────────────────────────
    {
        "name": "Buffalo Wings (6 pcs)",
        "category": "Starters",
        "cuisine": "american",
        "description": "Crispy chicken wings tossed in spicy buffalo sauce, served with blue cheese dip",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "hot",
        "allergens": "dairy, gluten",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Classic Fries, Classic Coleslaw",
    },
    {
        "name": "Mac & Cheese Bites",
        "category": "Starters",
        "cuisine": "american",
        "description": "Crispy fried macaroni and cheese balls with chipotle dipping sauce",
        "price": 200.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
        "meal_times": "snacks,brunch,lunch",
        "pairs_with": "Loaded Cheese Fries, Classic Milkshake",
    },
    {
        "name": "Caesar Salad",
        "category": "Starters",
        "cuisine": "american",
        "description": "Romaine lettuce with parmesan, croutons, and house Caesar dressing",
        "price": 220.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Garlic Bread, Fresh Lemonade",
    },
    # ─────────────────────────── AMERICAN — Mains ────────────────────────────
    {
        "name": "BBQ Pulled Pork Platter",
        "category": "Mains",
        "cuisine": "american",
        "description": "Slow-smoked pulled pork with hickory BBQ sauce, served with cornbread and coleslaw",
        "price": 420.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
        "pairs_with": "Classic Coleslaw, Loaded Cheese Fries",
    },
    {
        "name": "Grilled Ribeye Steak",
        "category": "Mains",
        "cuisine": "american",
        "description": "250g prime ribeye grilled to your preference, with garlic butter and fries",
        "price": 680.0,
        "is_vegetarian": False,
        "allergens": "dairy",
        "meal_times": "dinner",
        "pairs_with": "Garlic Bread, Caesar Salad",
    },
    {
        "name": "New York Style Pizza (12\")",
        "category": "Mains",
        "cuisine": "american",
        "description": "Classic hand-tossed pizza with mozzarella and your choice of toppings",
        "price": 380.0,
        "is_vegetarian": True,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "BBQ Chicken Pizza (12\")",
        "category": "Mains",
        "cuisine": "american",
        "description": "Smoky BBQ sauce with grilled chicken, red onions, and mozzarella",
        "price": 420.0,
        "is_vegetarian": False,
        "allergens": "gluten, dairy",
        "meal_times": "lunch,dinner",
    },
    {
        "name": "Penne Arrabbiata",
        "category": "Mains",
        "cuisine": "american",
        "description": "Penne pasta in a spicy tomato sauce with garlic and fresh basil",
        "price": 280.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "medium",
        "allergens": "gluten",
        "meal_times": "lunch,dinner",
        "pairs_with": "Garlic Bread, Caesar Salad",
    },
    # ─────────────────────────── AMERICAN — Beverages ────────────────────────
    {
        "name": "Classic Milkshake",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Thick and creamy shake — choose from Chocolate, Vanilla, or Strawberry",
        "price": 150.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "all",
    },
    {
        "name": "Fresh Lemonade",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Hand-squeezed lemonade with fresh mint",
        "price": 80.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "all",
    },
    {
        "name": "Fresh Orange Juice",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Freshly squeezed orange juice",
        "price": 100.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "breakfast,brunch,all",
    },
    {
        "name": "Americano Coffee",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Double-shot espresso with hot water",
        "price": 90.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "all",
    },
    {
        "name": "Cappuccino",
        "category": "Beverages",
        "cuisine": "american",
        "description": "Rich espresso with steamed milk and a thick layer of frothy milk foam",
        "price": 110.0,
        "is_vegetarian": True,
        "allergens": "dairy",
        "meal_times": "all",
    },
    {
        "name": "Craft Root Beer",
        "category": "Beverages",
        "cuisine": "american",
        "description": "House-made old-fashioned root beer",
        "price": 90.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "meal_times": "all",
    },
    # ─────────────────────────── AMERICAN — Desserts ─────────────────────────
    {
        "name": "New York Cheesecake",
        "category": "Desserts",
        "cuisine": "american",
        "description": "Dense and creamy New York-style cheesecake with berry compote",
        "price": 180.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
        "meal_times": "desserts,brunch,lunch,dinner",
        "pairs_with": "Americano Coffee, Cappuccino",
    },
    {
        "name": "Warm Brownie Sundae",
        "category": "Desserts",
        "cuisine": "american",
        "description": "Fudgy chocolate brownie with vanilla ice cream and hot fudge sauce",
        "price": 160.0,
        "is_vegetarian": True,
        "allergens": "dairy, gluten, eggs",
        "meal_times": "desserts,lunch,dinner",
        "pairs_with": "Americano Coffee, Cappuccino",
    },
    # ─────────────────────────── FUSION ──────────────────────────────────────
    {
        "name": "Tandoori Chicken Sandwich",
        "category": "Fusion",
        "cuisine": "fusion",
        "description": "Tandoor-grilled chicken with mint chutney, lettuce, and pickled onions on a toasted bun",
        "price": 300.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "gluten, dairy",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Masala Fries, Mango Lassi",
    },
    {
        "name": "Tikka Masala Wrap",
        "category": "Fusion",
        "cuisine": "fusion",
        "description": "Grilled chicken tikka with crunchy slaw and tikka mayo in a toasted flour tortilla",
        "price": 280.0,
        "is_vegetarian": False,
        "spice_level": "medium",
        "allergens": "gluten, dairy",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Masala Fries, Fresh Lime Soda",
    },
    {
        "name": "Masala Fries",
        "category": "Fusion",
        "cuisine": "fusion",
        "description": "Crispy fries tossed with chaat masala, lime, red chilli, and coriander",
        "price": 130.0,
        "is_vegetarian": True,
        "is_vegan": True,
        "spice_level": "medium",
        "allergens": "gluten",
        "meal_times": "snacks,lunch,dinner",
        "pairs_with": "Mango Lassi, Craft Root Beer",
    },
    {
        "name": "Paneer Quesadilla",
        "category": "Fusion",
        "cuisine": "fusion",
        "description": "Flour tortilla filled with spiced paneer, bell peppers, and melted mozzarella",
        "price": 260.0,
        "is_vegetarian": True,
        "spice_level": "mild",
        "allergens": "gluten, dairy",
        "meal_times": "brunch,lunch,dinner",
        "pairs_with": "Masala Fries, Fresh Lemonade",
    },
]


async def seed_menu() -> None:
    for item_data in MENU_DATA:
        await prisma.menuitem.create(data=item_data)
    print(f"Seeded {len(MENU_DATA)} menu items (Indian + American + Fusion)")


if __name__ == "__main__":
    async def main():
        await prisma.connect()
        try:
            await seed_menu()
        finally:
            await prisma.disconnect()

    asyncio.run(main())
