import json
import logging
from typing import Any, Dict, List, Optional

from app.services.groq.client import get_groq_client
from app.services.groq.prompts import (
    MEMORY_SUMMARIZE_PROMPT,
    ORDER_EXTRACTION_PROMPT,
    PREFERENCE_EXTRACTION_PROMPT,
    build_conversation_prompt,
)
from app.core.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


class ConversationService:
    """Handles all Groq-powered conversation tasks using Llama-3.1-8b-instant."""

    def _get_client(self):
        return get_groq_client()

    async def _generate(self, prompt: str, json_mode: bool = False) -> str:
        """
        Call the Groq Chat Completions API asynchronously.
        Natively async, so it doesn't block FastAPI's event loop.
        """
        client = self._get_client()
        messages = [{"role": "user", "content": prompt}]

        kwargs = {}
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        completion = await client.chat.completions.create(
            messages=messages,
            model=settings.groq_model,
            temperature=0.1,  # Lower temperature for more deterministic outputs
            **kwargs
        )
        response = completion.choices[0].message.content.strip()

        # Clean up any potential 'Aria:' prefix generated by the completion
        if response.startswith("Aria:"):
            response = response[len("Aria:"):].strip()
        return response

    async def chat(
        self,
        customer_name: Optional[str],
        preferences: Optional[Dict[str, Any]],
        menu_summary: str,
        current_order: Optional[Dict[str, Any]],
        recent_memories: List[str],
        conversation_history: List[Dict[str, str]],
        user_message: str,
    ) -> str:
        """Generate an AI concierge response."""
        prompt = build_conversation_prompt(
            customer_name=customer_name,
            preferences=preferences,
            menu_summary=menu_summary,
            current_order=current_order,
            recent_memories=recent_memories,
            conversation_history=conversation_history,
            user_message=user_message,
        )
        try:
            return await self._generate(prompt)
        except Exception as e:
            logger.error(f"Groq chat error: {e}")
            return (
                "I'm sorry, I'm having trouble processing your request right now. "
                "Could you please try again?"
            )

    async def extract_order_actions(
        self, message: str, menu_summary: str
    ) -> List[Dict[str, Any]]:
        """Extract structured order actions from a customer message."""
        # Escape curly braces in user message to prevent Python format-string injection
        safe_message = message.replace("{", "{{").replace("}", "}}")
        prompt = ORDER_EXTRACTION_PROMPT.format(
            menu_summary=menu_summary, message=safe_message
        )
        text = ""
        try:
            text = await self._generate(prompt, json_mode=True)
            actions = json.loads(text)
            if not isinstance(actions, list):
                actions = [actions]
            return actions
        except json.JSONDecodeError:
            logger.warning(f"Could not parse order extraction JSON: {text!r:.200}")
            return [{"action": "none"}]
        except Exception as e:
            logger.error(f"Order extraction error: {e}")
            return [{"action": "none"}]

    async def summarize_conversation(self, conversation: str) -> str:
        """Summarize a conversation into a memory fact."""
        prompt = MEMORY_SUMMARIZE_PROMPT.format(conversation=conversation)
        try:
            return await self._generate(prompt)
        except Exception as e:
            logger.error(f"Summarization error: {e}")
            return ""

    async def extract_preferences(self, summary: str) -> Dict[str, Any]:
        """Extract structured preferences from a conversation summary."""
        prompt = PREFERENCE_EXTRACTION_PROMPT.format(summary=summary)
        try:
            text = await self._generate(prompt, json_mode=True)
            return json.loads(text)
        except Exception as e:
            logger.error(f"Preference extraction error: {e}")
            return {}
